project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - tour.qmd
  resources:
    - CNAME
    - .nojekyll

website:
  title: "Academic Studio"
  search: false
  navbar: false

format:
  html:
    theme:
      light: flatly
      dark: superhero
    toc: true
