project:
  type: website
  output-dir: _site
  render:
    - index.qmd
    - tour.qmd
    - voiceovers.qmd
    - slides.qmd
    - finance-data.qmd
  resources:
    - CNAME
    - .nojekyll
    - packages.json
    - packages/

website:
  title: ""
  search: false
  navbar:
    search: false
    title: Academic Studio
    file: index.qmd
    right:
      - text: "Voiceovers"
        file: voiceovers.qmd
      - text: "Slides"
        file: slides.qmd
      - text: "Finance Data"
        file: finance-data.qmd

format:
  html:
    theme:
      light: flatly
      dark: superhero
    toc: true
